<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Учет посещений бассейна</title>
    <link rel="stylesheet" href="${currentContext}/static/css/styles.css">
</head>
<body>
<div class="welcome-container">
    <h1 class="welcome-title">
        Добро пожаловать на сайт учета посещений занятий физической культуры
        по плаванию студентов Казанского Федерального Университета!
    </h1>

    <div class="button-group">
        <a href="register" class="btn btn-register">Регистрация</a>
        <a href="login" class="btn">Вход</a>
    </div>
</div>
</body>
</html>